version: '3.8'

services:
  testapp:
    image: idfconnect-docker.jfrog.io/testweb:1.0
    container_name: testapp
    networks:
      - core-infra
    ports:
      - "8080:8080"
    volumes:
      - .\testapp\filter.properties:/usr/local/conf/filter.properties
      - .\testapp\testweb.xml:/usr/local/tomcat/conf/Catalina/localhost/testweb.xml
      - .\certs\keystore.jks:/container/certs/keystore.jks
networks:
  core-infra:
    external: true
    
secrets:
  ldap_secret:
    external: true
 