version: '3.8'

services:
  gw:
    image: idfconnect-docker.jfrog.io/ssorest-gw:3.2.0-SS
    networks:
      - core-infra
    container_name: gw
    ports:
      - "8180:8180"
    depends_on:
      - pe
    volumes:
      - ..\gw\apphome\conf32\:/opt/IDFC/SSORest/conf/
      - ..\gw\apphome\license\:/opt/IDFC/SSORest/license/
      - ..\certs\keystore.jks:/container/certs/keystore.jks
    environment:
      - appHome=/opt/IDFC/SSORest
      
networks:
  core-infra:
    external: true
