version: '3.8'

services:
  testapp:
    image: idfconnect-docker.jfrog.io/testweb:3.2.0
    # extra_hosts:
    #   - "docker:192.168.1.8"
    container_name: testapp
    networks:
      - core-infra
    ports:
      - "8080:8080"
    volumes:
      - ..\testapp\testapp32\filter.properties:/usr/local/conf/filter.properties
      - ..\testapp\testapp32\testweb.xml:/usr/local/tomcat/conf/Catalina/localhost/testweb.xml
      - ..\certs\keystore.jks:/container/certs/keystore.jks
networks:
  core-infra:
    external: true
    
secrets:
  ldap_secret:
    external: true
 