version: '3.8'

services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_secret
    volumes:
      - ..\mysql\data2:/var/lib/mysql
    secrets:
      - source: mysql_secret
        target: /run/secrets/mysql_secret

  adminer:
    image: adminer
    restart: always
    ports:
      - 8980:8080

networks:
  core-infra:
    external: true

secrets:
  mysql_secret:
    external: true
 